version: '3.5'

services:
  meeting-backend:
    container_name: SmartAgriculture
    image: app:1.0
    volumes:
      - /work/images:/work/images
      - /work/model:/work/model
    ports:
      - "8066:8066"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 500M
    restart: always
