server:
  servlet:
    context-path: /
  max-http-header-size: 204857600 #200M
#  ssl:
#    key-store: classpath:smart.pfx
#    key-store-password: z4XnNNc632c0
#    key-store-type: pkcs12
#    enabled: true
  port: 8066
  tomcat:
    connection-timeout: 18000000
spring:
  security:
    user:
      name: admin
      password: 123456
  application:
    name: Smart_agriculture
  profiles:
    active: dev
model:
  path: D:\\应用缓存文件\\QQ\\model.onnx
  threads: 1

# MP配置日志
logging:
  level:
    root: info
    com.jhc.mapper: debug
    com.jhc.service: debug
    com.jhc.config: debug
    com:
      company:
        cache: debug


web:
  all-images: file:/work/images/
  all-images-mapping: /images/**
  images: /work/images/
  photo: 0963a765614f9123b71bd48b4b9a2a69
  images-mapping: /images
  files: /image/
  images-suffix: >
    .JPG,
    .JPEG,
    .PNG,
    .GIF,
    .BMP
