server:
  #  port: 8080
  servlet:
    context-path: /
  max-http-header-size: 204857600 #200M
jasypt:
  encryptor:
    password: JHCDJEWT
spring:
  security:
    user:
      name: admin
      password: 123456
  application:
    name: Smart_agriculture
  profiles:
    active: dev
model:
  path: D:\\应用缓存文件\\QQ\\model.onnx
  threads: 1

web:
  all-images: file:/work/images/
  all-images-mapping: /images/**
  images: /work/images/
  photo: 0963a765614f9123b71bd48b4b9a2a69
  images-mapping: /images
  files: /image/
  images-suffix: >
    .JPG,
    .JPEG,
    .PNG,
    .GIF,
    .BMP